import LoginForm from '@/modules/login/LoginForm';
import { RootState } from '@/store';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';

const Home: NextPage = () => {
  const user = useSelector((state: RootState) => state.user.user);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      {!user ?
        <LoginForm />
        : <></>}
    </div>
  )
}

export default Home
